### ISSUE TITLE
Reduce box size

### ISSUE THREAD

**Issue by stopiccot** [AndrewDryga/vagrant-box-osx#10]
Btw, have you tried:

    diskutil secureErase freespace 0 Macintosh\ HD

before packaging the box? Because similar box (osx + xcode) is only 9Gb for me.

**Comment by AndrewDryga** [comment]
Yosemite even after this command is 14 GB :(

**Comment by AndrewDryga** [comment]
@stopiccot done, Yosemite box it's 9Gb now. Thanks.

(Also using VDI instead of VHDI saves about 2 GB. And I've removed some screensavers, speech synthesizers, etc.)
