### ISSUE TITLE
Can't accept Xcode license agreement

### ISSUE THREAD

**Issue by mararual** [AndrewDryga/vagrant-box-osx#15]
Hi,

Thanks for creating this box. I'm having a problem when trying to accept the XCode license agreements using vagrant ssh. I get this:

vagrant:~ vagrant$ sudo xcodebuild 

You have not agreed to the Xcode license agreements. You must agree to both license agreements below in order to use Xcode.

Hit the Enter key to view the license agreements at '/Applications/Xcode.app/Contents/Resources/English.lproj/License.rtf'
**************************************

However, after pressing enter several times, it just doesn't do aything. It doesn;t show the License agreement. Never. So I can't accept it and I'm stuck. Thought It may had something to do with LC_* env variables or something like that. 

Any ideas as to how I can proceed?

Thanks for your help!

**Comment by AndrewDryga** [comment]
New box have accepted license by default, also I will keep acception instructions in Readme. (Tnx to @stopiccot)
