### ISSUE TITLE
Vagrantfile ?

### ISSUE THREAD

**Issue by brandondrew** [AndrewDryga/vagrant-box-osx#16]
It would be useful to include a default Vagrantfile which has the URL included (so it downloads the file if it's not already installed with a `vagrant box add ...` command).

**Comment by AndrewDryga** [comment]
Done.
Also you can use ```vagrant init http://files.dryga.com/boxes/osx-yosemite-0.2.0.box``` to start without adding box alias.

**Comment by alexszilagyi** [comment]
@AndrewDryga : I'm getting 404 Not Found error, do you have the file somewhere else?

**Comment by AndrewDryga** [comment]
@alexszilagyi Does http://files.dryga.com/boxes/osx-yosemite-0.2.1.box this one fits your needs? It's also Yosemite, but with never XCode version.

**Comment by alexszilagyi** [comment]
@AndrewDryga : ok. Thank you! 👍
