### ISSUE TITLE
iPad Simulators missing

### ISSUE THREAD

**Issue by rahulsom** [AndrewDryga/vagrant-box-osx#18]
When I launch XCode, I only see iPhone Simulators. Is there a config I'm missing? Or do I need to run something to download one?

**Comment by rahulsom** [comment]
I had to run this command

```shell
xcrun simctl create "iPad 2" "iPad 2" "com.apple.CoreSimulator.SimRuntime.iOS-8-1"
```

**Comment by AndrewDryga** [comment]
I think its missing because i've deleted it to save memory (anyone who needs it can add it manually). If its critical for you - tell me, I will add it in future versions

**Comment by rahulsom** [comment]
Current approach sounds good. Thanks!
