### ISSUE TITLE
password?

### ISSUE THREAD

**Issue by levelos** [AndrewDryga/vagrant-box-osx#19]
What's the vagrant user's password? After being idle for a bit, OS X requires a login. Could this be configurable? Thanks!

**Comment by WayneBuckhanan** [comment]
I just tested and confirmed the password for the vagrant user is the typical "vagrant" (w/o quotes).

I feel like I'm missing something obvious -- how are you getting a GUI from this vagrant box? 
I'm using it as commandline only so far...

**Comment by AndrewDryga** [comment]
@levelos Hi. User and password is default for Vagrant (vagrant:vagrant) and this user have paswordless sudo.

@WayneBuckhanan to start in GUI mode you should change ```vb.gui``` flag to ```true```. Here it is: https://github.com/AndrewDryga/vagrant-box-osx/blob/master/Vagrantfile#L22

**Comment by levelos** [comment]
Thanks Andrew, I didn't realize it was that obvious :)
