### ISSUE TITLE
Working on non-apple hardware?

### ISSUE THREAD

**Issue by Ramblurr** [AndrewDryga/vagrant-box-osx#21]
Are there any reports of this box working on non-apple hardware, specifically in a Linux host?

In headless mode the box boots fine, but in GUI mode the box won't boot getting stuck at "missing bluetooth controller transport". I'm guessing that's a red herring though, it is probably related to my intel chipset/graphics.

**Comment by Ramblurr** [comment]
Ah, some more googling solved it for me. You need to set the proper DMI info with setextradata.

**Comment by jadjoubran** [comment]
How did you fix it? I'm getting the same issue on Ubunutu 14.04

**Comment by WayneBuckhanan** [comment]
@jadjoubran: see my [OSX Vagrantfile](https://gist.github.com/WayneBuckhanan/15de1bb8b3fb3bd4f7af)
