### ISSUE TITLE
GUI mode?

### ISSUE THREAD

**Issue by harishworks** [AndrewDryga/vagrant-box-osx#26]
How I can run GUI mode?, it fires up console mode and able to ssh into it.

**Comment by SpaceK33z** [comment]
Take a look at the [Vagrant docs](https://docs.vagrantup.com/v2/virtualbox/configuration.html).

**Comment by justinr1234** [comment]
Setting GUI mode from the vagrant file doesn't bring up anything useful.

![image](https://cloud.githubusercontent.com/assets/7017500/8756680/0829df52-2ca2-11e5-9e67-db917fd51f56.png)

**Comment by harishworks** [comment]
I am facing the same issue.

**Comment by WayneBuckhanan** [comment]
I was stuck there for way too long before I figured out the cpuid and graphics mode to pass in via the Vagrantfile.

See https://gist.github.com/WayneBuckhanan/15de1bb8b3fb3bd4f7af for the various details all collected in one place.

**Comment by AndrewDryga** [comment]
Hi guys. In new box I've already set cpu, and It worked in GUI mode for me and some other people.

@WayneBuckhanan did your customizations solve the problem?
```
    vb.customize ["setextradata", :id, "VBoxInternal/Devices/efi/0/Config/DmiSystemProduct", "MacBookPro11,3"]
    vb.customize ["setextradata", :id, "VBoxInternal/Devices/efi/0/Config/DmiSystemVersion", "1.0"]
    vb.customize ["setextradata", :id, "VBoxInternal/Devices/efi/0/Config/DmiBoardProduct", "Iloveapple"]
    vb.customize ["setextradata", :id, "VBoxInternal/Devices/smc/0/Config/DeviceKey", "ourhardworkbythesewordsguardedpleasedontsteal(c)AppleComputerInc"]
    vb.customize ["setextradata", :id, "VBoxInternal/Devices/smc/0/Config/GetKeyFromRealSMC", "1"]

```

**Comment by AndrewDryga** [comment]
I've updated the box, @harishworks does it work now?

**Comment by WayneBuckhanan** [comment]
Yes, @AndrewDryga, those customizations solved the problem. I suspect it had been because I was running it on non-standard hardware.

**Comment by AndrewDryga** [comment]
Awesome. I'll close this issue. Also I've included this customizations to latest box version.
