### ISSUE TITLE
can not creat at win10

### ISSUE THREAD

**Issue by foxundermoon** [AndrewDryga/vagrant-box-osx#27]
this  is my log
https://gist.github.com/foxundermoon/c9761a4252b9f7e77955

**Comment by AndrewDryga** [comment]
Unfortunately, I don't have any Windows machines and can't reproduce this issue. As I know VirtualBox doesn't guarantee that VM's with MacOS would work on Windows or Linux hosts.

P.S.: Using this box on non-Apple hardware violates Apple EULA.
