### ISSUE TITLE
Port forwarding not working

### ISSUE THREAD

**Issue by nutrina** [AndrewDryga/vagrant-box-osx#32]
Hello,

I was just testing this VM, and it seems that I am having an issue with the port forwarding for ssh I think. I have tried to set this up on a Linux host, and this is the output I get:

![1__root_h2359578___var_vagrant_test_test__ssh_](https://cloud.githubusercontent.com/assets/8137830/11451872/510c4cf6-95dd-11e5-9a06-a4394970cd3f.png)

Also, I am not able to run (I assume this should work since the ssh port is forwarded to 2222):

    ssh 127.0.0.1 -p 2222

Have anyone else encountered this, or has anyone else even tried a Linux host? Do you have any recommendation on how to fix this?

Thanks,
Gerald

**Comment by AndrewDryga** [comment]
Hello, 

Did you tried to turn off headless mode and to look what's happening on VM screen? This can happen when VM simply can't boot.
