### ISSUE TITLE
Little video memory

### ISSUE THREAD

**Issue by Ricky-Gong** [AndrewDryga/vagrant-box-osx#33]
Hello, everyone.

The guest machine only has 3MB video memory even though I set it to be 128MB in Virtualbox. I got this figure from "About this computer". And therefore I got bad windows display and laggy mouse movement. I searched for solution on the Internet but nothing useful has been found.

Does anyone know how to fix this problem?

**Comment by AndrewDryga** [comment]
Hello,

This looks like a VirtualBox bug, since box itself doesn't affect how much video memory should be provided by default. Maybe try to update VirtualBox or to turn 3D-Acceleration on? (Don't forget to turn it back off, since VM won't boot in headless mode.)
