### ISSUE TITLE
The box 'http://files.dryga.com/boxes/osx-yosemite-0.2.1.box' could not be found.

### ISSUE THREAD

**Issue by demiters** [AndrewDryga/vagrant-box-osx#36]
arturs@arturs:~/git/osx$ vagrant init http://files.dryga.com/boxes/osx-yosemite-0.2.1.box
A `Vagrantfile` has been placed in this directory. You are now
ready to `vagrant up` your first virtual environment! Please read
the comments in the Vagrantfile as well as documentation on
`vagrantup.com` for more information on using Vagrant.
arturs@arturs:~/git/osx$ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
There are errors in the configuration of this machine. Please fix
the following errors and try again:

vm:
- The box 'http://files.dryga.com/boxes/osx-yosemite-0.2.1.box' could not be found.

What's the matter here?

**Comment by AndrewDryga** [comment]
Hi. It seems like some connectivity issues.

Does download start if you follow that link from your browser?

**Comment by teocci** [comment]
I have the same problem I donwloaded the file directly and I'm still having the same message:

> vm:
    The box 'http://files.dryga.com/boxes/osx-yosemite-0.2.1.box' could not be found.

**Comment by AndrewDryga** [comment]
@teocci can you, please, provide your Vagrantfile?
