### ISSUE TITLE
changing VM memory to 4096 makes in unbootable

### ISSUE THREAD

**Issue by stopiccot** [AndrewDryga/vagrant-box-osx#4]
Adding

    config.vm.provider "virtualbox" do |v|
      v.memory = 4096
    end

to Vagrantfile makes VM unbootable.

I understand that it can be more a vagrant/virtualbox issue than your box issue but maybe you can help with it.

**Comment by AndrewDryga** [comment]
Tried to reproduce it on Yosemite, everything works fine. Can you confirm that problem solved on latest box+vagrant+virtualbox?

**Comment by electricjesus** [comment]
I've seen this happen to me by mistake as well.

I only have 4GB total memory in one machine, and my other machine has 8GB. Working primarily on my 8GB machine I did set it to 4096. I then used the same Vagrantfile on the 4GB one so what happened is that VBox can't commit to that much memory (Vbox still starts without a hitch), then OSX hits guru meditation.

**Comment by AndrewDryga** [comment]
Thanks for report, I will close this issue :)
