### ISSUE TITLE
Host box in git LFS

### ISSUE THREAD

**Issue by michaelsanford** [AndrewDryga/vagrant-box-osx#40]
I'm unsure if this is feasible, but perhaps the box could be committed and hosted using [git LFS (Large File Store).](https://git-lfs.github.com/)

It could provide a more available location to host the box.

**Comment by AndrewDryga** [comment]
Github LFS is a paid feature, all box versions is about 45 Gb in size and they consume around 1 000 Gb in traffic.

**Comment by michaelsanford** [comment]
I hadn't realized it was paid; understandable but seems prohibitive.
