### ISSUE TITLE
insert_key and post_up_message issue

### ISSUE THREAD

**Issue by teocci** [AndrewDryga/vagrant-box-osx#41]
After using "vagrant up" I got the following output

> Bringing machine 'default' up with 'virtualbox' provider...
> [default] Box 'osx-yosemite-0.2.1.box' was not found. Fetching box from specified URL for
> the provider 'virtualbox'. Note that if the URL does not have
> a box for this provider, you should interrupt Vagrant now and add
> the box yourself. Otherwise Vagrant will attempt to download the
> full box prior to discovering this error.
> Downloading box from URL: http://localhost/boxes/osx-yosemite-0.2.1.box
> Extracting box...te: 30.1M/s, Estimated time remaining: 0:00:02)
> Successfully added box 'osx-yosemite-0.2.1.box' with provider 'virtualbox'!
> There are errors in the configuration of this machine. Please fix
> the following errors and try again:
> 
> SSH:
> - The following settings shouldn't exist: insert_key
> 
> vm:
> - The following settings shouldn't exist: post_up_message

**Comment by teocci** [comment]
I solved this problem modifying the file locate in the "$HOME/.vagrant.d/boxes/osx-yosemite-0.2.1.box/virtualbox/_Vagrantfile"

Just comment this two lines:

>     # Temporary fix for annoying "Replace key" issue
>     #config.ssh.insert_key = false
> 
>     # Set welcome message
>     #config.vm.post_up_message = "Welcome to Mac OS X Yosemite box."

**Comment by AndrewDryga** [comment]
Will be fixed in newest sierra box.

**Comment by joe-nano** [comment]
Hello Andrew do you have box for mountain lion? I'm looking to build one for research that requires a laser that is only built to work on mac os x 10.9.5 and below. I got it working on mavericks but I noticed you don't have a vagrant box for that or do you? Thank you for your work.
