### ISSUE TITLE
can't play MP4 in Safari/Quicktime

### ISSUE THREAD

**Issue by tomByrer** [AndrewDryga/vagrant-box-osx#42]
Seems Safari & Quicktime in the VM doesn't like to play MP4 videos for some reason.  YouTube works, but I suspect they use a different format, or segment the videos into smaller blocks.  Chrome inside the same VM, & Safari on the same machine outside of the VM works just fine.  1 Mb video size still fail.  Example:
http://www.sample-videos.com/index.php#sample-mp4-video

**Comment by tomByrer** [comment]
Further testing; direct links to video worked, as well as older `<embed>` HTML video tags.

**Comment by AndrewDryga** [comment]
I think it may be because of VirtualBox 3D acceleration settings. Did you tried to turn it on and to add some video RAM?

**Comment by tomByrer** [comment]
No because Readme "Do not turn 3D acceleration on in VirtualBox, or it will
start retuning aborted condition and would not start in headless mode;"
Should I try?

**Comment by AndrewDryga** [comment]
Yes, but start VM in GUI mode. It will help you to check whenever it's a 3D acceleration issue.
