### ISSUE TITLE
Cannot change host screen resolution

### ISSUE THREAD

**Issue by Geremia** [AndrewDryga/vagrant-box-osx#44]
I have VirtualBox set to "hint" at a higher resolution, but, still, I can't get the house to use anything other than 1024×768.

**Comment by ob7** [comment]
Any insight on fixing this?  I have same need.

**Comment by rootion** [comment]
VirtualBox doesn't have Guest additions for Mac OS X, which is the usual way to change the default resolution. Does anyone know if there any workaround?

**Comment by rootion** [comment]
@ob7 Thanks so much. I got it working in a linux host using the same commands you provided.

**Comment by AndrewDryga** [comment]
Adding this to vagrantfile sample.
