### ISSUE TITLE
Seamless mode doesn't seem to work

### ISSUE THREAD

**Issue by nitrocode** [AndrewDryga/vagrant-box-osx#45]
Hi! I'm trying to run OSX VM on top of OSX Host so that my main desktop is clean and the VM can be easily destroyed and recreated.

I'm trying to make the dock and top bar seamless so that I can touch the OSX Host dock and the OSX VM but Virtualbox's seamless mode is grayed out. Is this an issue with the box, with Virtualbox, or with my setup?

Thanks

**Comment by AndrewDryga** [comment]
Hello.

Inside box there is a very basic Mac OS version with very few additions. I think its because VirtualBox support for Mac OS is experimental and not all features is available.

**Comment by nitrocode** [comment]
Oh ok, that makes sense. I guess it's on the Virtualbox side then. If I have time, I'll try to find a ticket on their side or create one and attach it here.
