### ISSUE TITLE
osx-sierra-0.3.1.box seems to be corrupted.

### ISSUE THREAD

**Issue by cristafortuno** [AndrewDryga/vagrant-box-osx#47]
Hi,

I've downloaded the osx-sierra box (direct link download) and after trying to add the box, the following error is encountered:

cristaa.fortuno$ vagrant box add ~/Downloads/osx-sierra-0.3.1.box --name osx-sierra-0.3.1.box
==> box: Box file was not detected as metadata. Adding it directly...
==> box: Adding box 'osx-sierra-0.3.1.box' (v0) for provider: 
    box: Unpacking necessary files from: file:///Users/cristaa.fortuno/Downloads/osx-sierra-0.3.1.box
The box failed to unpackage properly. Please verify that the box
file you're trying to add is not corrupted and try again. The
output from attempting to unpackage (if any):

x ./box-disk1.vmdk: truncated gzip input
bsdtar: Error exit delayed from previous errors.

Kindly advise. Thank you.

**Comment by syntaxerror** [comment]
Seems like I have the same issue, on Ubuntu Linux 16.04
VirtualBox 5.1.10r112026 (Qt5.5.1)
Vagrant 1.8.7

> vagrant up
> Bringing machine 'default' up with 'virtualbox' provider...
> ==> default: Box 'osx-sierra-0.3.1.box' could not be found. Attempting to find and install...
>     default: Box Provider: virtualbox
>     default: Box Version: >= 0
> ==> default: Box file was not detected as metadata. Adding it directly...
> ==> default: Adding box 'osx-sierra-0.3.1.box' (v0) for provider: virtualbox
>     default: Unpacking necessary files from: file:///VirtualBoxVMs/Mac/osx-sierra-0.3.1.box
> The box failed to unpackage properly. Please verify that the box
> file you're trying to add is not corrupted and try again. The
> output from attempting to unpackage (if any):
> 
> x ./box-disk1.vmdk: truncated gzip input
> bsdtar: Error exit delayed from previous errors.

**Comment by AndrewDryga** [comment]
Hello,

I guess there was an error on file upload, I'll try to do it again in few hours.

**Comment by cristafortuno** [comment]
Hi Andrew,

Thanks! Will wait for your update.

**Comment by AndrewDryga** [comment]
@cristafortuno I have re-uploaded box file. Can you try to bring it up again?

**Comment by cristafortuno** [comment]
@AndrewDryga Downloading...will update you of result at once. Many thanks!

**Comment by cristafortuno** [comment]
@AndrewDryga Box was successfully added. Thanks!

**Comment by AndrewDryga** [comment]
Awesome, thanks for testing! 👍

**Comment by gabmontes** [comment]
@AndrewDryga I'm running into the same issue. Can you please confirm the shasum of the box file to check it was properly downloaded? I will try to download again, anyway.

Ubuntu 16.04 64-bit
Vagrant 1.9.5
VirtualBox 5.1.22 r115126

PS: Thanks for these awesome resources!!

**Comment by AndrewDryga** [comment]
@gabmontes Hello, checksum is:
```
$ sha1sum osx-sierra-0.3.1.box 
e02ea7fff9c3af980bfa733c8feb2e03bf562cfd  osx-sierra-0.3.1.box
```

**Comment by gabmontes** [comment]
@AndrewDryga thanks!!!

**Comment by gabmontes** [comment]
@AndrewDryga I was finally able to download the whole file, shasum matches and VM is up! Please consider adding shasums to the `README.md` just in case someone else has the same problem.

Thanks again!!
