### ISSUE TITLE
Failing to boot

### ISSUE THREAD

**Issue by mooreandrew** [AndrewDryga/vagrant-box-osx#48]
I'm trying to run this and am getting the following error:

https://s24.postimg.org/xm428cc11/Virtual_Box_process_default_1482619205243_31827_2.png

Windows 10
Intel Pentium G3258
16GB ram

My vagrant file is the one from the src/include folder.

I have got this working on another PC which is a Intel Pentium I7 4790k, I'm not sure what is causing the error above.

**Comment by AndrewDryga** [comment]
Don't use that file, It's already packaged into box. The right one is here: https://github.com/AndrewDryga/vagrant-box-osx/blob/master/Vagrantfile

With this specific issue you can try to play with VirtualBox settings (cpu, chipset settings, provide more resources). This looks like a VirtualBox Mac Guest specific issue.

**Comment by mooreandrew** [comment]
You're right, thank you. It was Nested Paging I had to disable.

Do you know how I set this to disable in the Vagrantfile?

**Comment by AndrewDryga** [comment]
You can try 
`config.vm.customize ["modifyvm", :id, "--nestedpaging", "off"`

If it works, please, provide some additional details about VirtualBox, Vagrant version of your Intel Pentium G3258 machine, and versions for another one. I will add it to knowledge base later.

**Comment by mooreandrew** [comment]
Yes that worked, thanks.

Whilst debugging I updated both machines to the latest version of vagrant (1.9.1) and virtualbox (5.1.12). The issue happen on the G3258 prior to updating this evening, and the last time I probably updated was between 6 months and a year ago.

**Comment by AndrewDryga** [comment]
Thanks! 👍
