### ISSUE TITLE
VBoxManage.exe: error: Appliance import failed

### ISSUE THREAD

**Issue by brettstack** [AndrewDryga/vagrant-box-osx#5]
I'm getting this error on `vagrant up`, running on Windows 8.1, VirtualBox 4.3.10, Vagrant 1.6.0.

The only modifications I made to the `Vagrantfile` aside from setting `config.vm.box` was:

```
config.vm.provider "virtualbox" do |vb|
    # Don't boot with headless mode
    vb.gui = true

    # Use VBoxManage to customize the VM. For example to change memory:
    vb.customize ["modifyvm", :id, "--memory", "2048"]
  end
```

Command line output:

```
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'AndrewDryga/osx-mavericks'...
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["import", "C:/Users/Brett/.vagrant.d/boxes/AndrewDryga-VAGRANTSLASH-osx-mavericks/0.1.0/virtualbox/box.ovf", "
--vsys", "0", "--vmname", "Mac OS X - Vagrant_1399530920457_82370", "--vsys", "0", "--unit", "8", "--disk", "C:\\Users\\
Brett\\VirtualBox VMs\\Mac OS X - Vagrant\\box-disk1_1.vmdk"]

Stderr: 0%...10%...20%...30%...40%...50%...60%...70%...80%...90%...100%
Interpreting C:\Users\Brett\.vagrant.d\boxes\AndrewDryga-VAGRANTSLASH-osx-mavericks\0.1.0\virtualbox\box.ovf...
OK.
0%...
Progress state: VBOX_E_FILE_ERROR
VBoxManage.exe: error: Appliance import failed
VBoxManage.exe: error: Could not create the clone medium 'C:\Users\Brett\VirtualBox VMs\Mac OS X - Vagrant\box-disk1_1.v
mdk'.
VBoxManage.exe: error: VMDK: cannot write allocated data block in 'C:\Users\Brett\VirtualBox VMs\Mac OS X - Vagrant/box-
disk1_1.vmdk' (VERR_DISK_FULL)
VBoxManage.exe: error: Details: code VBOX_E_FILE_ERROR (0x80bb0004), component Appliance, interface IAppliance
VBoxManage.exe: error: Context: "int __cdecl handleImportAppliance(struct HandlerArg *)" at line 779 of file VBoxManageA
```

**Comment by usman101** [comment]
I am getting the same issue. Anyone solved this so far?

**Comment by myothandatoe-frobom** [comment]
I faced same problem because of having two vagrant files in same folder for my project.

**Comment by Fanweilin1** [comment]
`C:\Users\fanwe>vagrant init centos/7
A `Vagrantfile` has been placed in this directory. You are now
ready to `vagrant up` your first virtual environment! Please read
the comments in the Vagrantfile as well as documentation on
`vagrantup.com` for more information on using Vagrant.

C:\Users\fanwe>vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'centos/7' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
==> default: Loading metadata for box 'centos/7'
    default: URL: https://vagrantcloud.com/centos/7
==> default: Adding box 'centos/7' (v2004.01) for provider: virtualbox
    default: Downloading: https://vagrantcloud.com/centos/boxes/7/versions/2004.01/providers/virtualbox.box
Download redirected to host: cloud.centos.org
    default:
    default: Calculating and comparing box checksum...
==> default: Successfully added box 'centos/7' (v2004.01) for 'virtualbox'!
==> default: Importing base box 'centos/7'...
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["import", "\\\\?\\C:\\Users\\fanwe\\.vagrant.d\\boxes\\centos-VAGRANTSLASH-7\\2004.01\\virtualbox\\box.ovf", "--vsys", "0", "--vmname", "centos-7-1-1.x86_64_1684577567859_84128", "--vsys", "0", "--unit", "10", "--disk", "D:/Program Files/Oracle/VirtualBox/centos-7-1-1.x86_64_1684577567859_84128/centos-7-1-1.x86_64.vmdk"]

Stderr: 0%...10%...20%...30%...40%...50%...60%...70%...80%...90%...100%
Interpreting \\?\C:\Users\fanwe\.vagrant.d\boxes\centos-VAGRANTSLASH-7\2004.01\virtualbox\box.ovf...
OK.
0%...
Progress state: E_FAIL
VBoxManage.exe: error: Appliance import failed
VBoxManage.exe: error: Could not create a directory 'D:\Program Files\Oracle\VirtualBox\centos-7-1-1.x86_64_1684577567859_84128' to save the settings file (VERR_ACCESS_DENIED)
VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component MachineWrap, interface IMachine
VBoxManage.exe: error: Context: "enum RTEXITCODE __cdecl handleImportAppliance(struct HandlerArg *)" at line 957 of file VBoxManageAppliance.cpp`
