### ISSUE TITLE
Black Screen / Doesn't boot?

### ISSUE THREAD

**Issue by syntaxerror** [AndrewDryga/vagrant-box-osx#52]
I wonder if anyone has been able to run this on a computer with a AMD CPU (and 64 bit Ubuntu Linux)?
On my system I just get a black screen (in VirtualBox), it doesn't seem to boot properly.

My system:
AMD Phenom(tm) II X4 965 Processor × 4 
GeForce GT 640/PCIe/SSE2
32 GB RAM

I would recall I've read something some time ago, that it's easier to get Mac up running on Intel, even in VirtualBox etc.

**Comment by syntaxerror** [comment]
Using vagrant up, and waiting for a long time:

> vagrant up
> Bringing machine 'default' up with 'virtualbox' provider...
> ==> default: Clearing any previously set forwarded ports...
> ==> default: Clearing any previously set network interfaces...
> ==> default: Preparing network interfaces based on configuration...
>     default: Adapter 1: nat
> ==> default: Forwarding ports...
>     default: 22 (guest) => 2222 (host) (adapter 1)
> ==> default: Running 'pre-boot' VM customizations...
> ==> default: Booting VM...
> ==> default: Waiting for machine to boot. This may take a few minutes...
>     default: SSH address: 127.0.0.1:2222
>     default: SSH username: vagrant
>     default: SSH auth method: private key
> Timed out while waiting for the machine to boot. This means that
> Vagrant was unable to communicate with the guest machine within
> the configured ("config.vm.boot_timeout" value) time period.
> 
> If you look above, you should be able to see the error(s) that
> Vagrant had when attempting to connect to the machine. These errors
> are usually good hints as to what may be wrong.
> 
> If you're using a custom box, make sure that networking is properly
> working and you're able to connect to the machine. It is a common
> problem that networking isn't setup properly in these boxes.
> Verify that authentication configurations are also setup properly,
> as well.
> 
> If the box appears to be booting properly, you may want to increase
> the timeout ("config.vm.boot_timeout") value.

**Comment by AndrewDryga** [comment]
Did you tried to turn GUI mode on and look whats happening? Can you provide your Vagrantfile?

**Comment by syntaxerror** [comment]
Yes, the problem is nothing seems to happen. Starting directly from VirtualBox or Vagrant with GUI seems to do the same:
![vb_mac](https://cloud.githubusercontent.com/assets/858132/21611472/9aa8e754-d1d5-11e6-9b6f-2b92ed8e9131.png)

Haven't changed anything in Vagrantfile, and honestly, I don't know if I should. :)
`# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://atlas.hashicorp.com/search.
  config.vm.box = "/VirtualBoxVMs/Mac/osx-sierra-0.3.1.box"

  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  # config.vm.box_check_update = false

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # config.vm.network "forwarded_port", guest: 80, host: 8080

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # config.vm.network "private_network", ip: "192.168.33.10"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  # config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
  #   vb.gui = true
  #
  #   # Customize the amount of memory on the VM:
  #   vb.memory = "1024"
  # end
  #
  # View the documentation for the provider you are using for more
  # information on available options.

  # Define a Vagrant Push strategy for pushing to Atlas. Other push strategies
  # such as FTP and Heroku are also available. See the documentation at
  # https://docs.vagrantup.com/v2/push/atlas.html for more information.
  # config.push.define "atlas" do |push|
  #   push.app = "YOUR_ATLAS_USERNAME/YOUR_APPLICATION_NAME"
  # end

  # Enable provisioning with a shell script. Additional provisioners such as
  # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
  # documentation for more information about their specific syntax and use.
  # config.vm.provision "shell", inline: <<-SHELL
  #   apt-get update
  #   apt-get install -y apache2
  # SHELL
end`

**Comment by syntaxerror** [comment]
The log file
[VBox.log.zip](https://github.com/AndrewDryga/vagrant-box-osx/files/683085/VBox.log.zip)

But I also noticed in https://www.virtualbox.org/manual/ch03.html#intro-macosxguests
> This allows you to install and execute unmodified versions of Mac OS X **on supported host hardware**.
- wondering about this "supported hardware" ...

**Comment by WayneBuckhanan** [comment]
FYI, you may need more vb.customize fields if you are pushing the boundaries on what is "supported hardware"...
See [this gist](https://gist.github.com/WayneBuckhanan/15de1bb8b3fb3bd4f7af) for a Vagrant file that worked on a previous version of this box (haven't tested recently).

HTH

**Comment by syntaxerror** [comment]
OK, thanks for the info. Seems like there is need for quite much searching, reading, customisation and testing to get this up running on a system like mine. Maybe I'll just find a used Mac to do the web testing on instead. :)

**Comment by AndrewDryga** [comment]
I think it would help if you will submit issue on VirtualBox forums/support, because it can affect other users. 
Maybe they will be able to fix it in next releases or suggest you what is going on.

**Comment by syntaxerror** [comment]
You're probably right. I also tested adding a virtual Mac on a Windows host, it doesn't freez, but beyond that it seems to be same issues - meaning there is something about VirtualBox and Mac guests (maybe related to AMD etc, but have no Intel to verify).

**Comment by xoogu** [comment]
Can confirm this is an AMD specific problem. Doesn't work on my AMD based PC, but boots OK on my Intel laptop. Since OSX is only designed to work on Macs (which have Intel processors), not too surprising I guess.

**Comment by adhikjoshi** [comment]
I have same issue, Not working on AMD Cpu

**Comment by rkitover** [comment]
Any chance someone could use some of the AMD hackintosh magic to make things work?

**Comment by syntaxerror** [comment]
Personally I gave up the hole Vagrant thing long time ago, bought a cheap used MacBook Pro instead for web testing ...

**Comment by vanishtachangea** [comment]
Did anyone solve this issue?
I have Ubuntu 18.04.1 LTS and I am using a Virtual Box with Linux 16.04 with Vagrant because Hyperledger is not supported on Ubuntu 18.
But now, Ubuntu does not appear to be loading in the virtual Box, I'm gettng the black screen. 
I can do Vagrant ssh into the VM etc... But I cannot use the Virtual Box at all apart from running commands. 
Any help please?
Thanks.
