### ISSUE TITLE
Image goes directly to 'Guru meditation' (crashes on boot)

### ISSUE THREAD

**Issue by DavidVentura** [AndrewDryga/vagrant-box-osx#53]
```shell
➜ vagrant init http://files.dryga.com/boxes/osx-sierra-0.3.1.box
A `Vagrantfile` has been placed in this directory. You are now
ready to `vagrant up` your first virtual environment! Please read
the comments in the Vagrantfile as well as documentation on
`vagrantup.com` for more information on using Vagrant.
➜ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'http://files.dryga.com/boxes/osx-sierra-0.3.1.box' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
==> default: Box file was not detected as metadata. Adding it directly...
==> default: Adding box 'http://files.dryga.com/boxes/osx-sierra-0.3.1.box' (v0) for provider: virtualbox
    default: Downloading: http://files.dryga.com/boxes/osx-sierra-0.3.1.box
==> default: Box download is resuming from prior download progress
==> default: Successfully added box 'http://files.dryga.com/boxes/osx-sierra-0.3.1.box' (v0) for 'virtualbox'!
==> default: Importing base box 'http://files.dryga.com/boxes/osx-sierra-0.3.1.box'...
==> default: Matching MAC address for NAT networking...
==> default: Setting the name of the VM: osx_default_1484270183749_84366
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
The guest machine entered an invalid state while waiting for it
to boot. Valid states are 'starting, running'. The machine is in the
'gurumeditation' state. Please verify everything is configured
properly and try again.

If the provider you're using has a GUI that comes with it,
it is often helpful to open that and watch the machine, since the
GUI often has more helpful error messages than Vagrant can retrieve.
For example, if you're using VirtualBox, run `vagrant up` while the
VirtualBox GUI is open.

The primary issue for this error is that the provider you're using
is not properly configured. This is very rarely a Vagrant issue.
```

This is on linux with Virtualbox 5.0 and Virtualbox 5.1

Log : http://pastebin.com/HbWBp4Av (4k lines...). I tried setting ignore_msrs to 1 as is needed with kvm

**Comment by syntaxerror** [comment]
I think it's Virtualbox 5 Mac issue, not related to this box. You can test without the box, using any of the Mac boots available on the net, and get the same result. https://github.com/AndrewDryga/vagrant-box-osx/issues/52

**Comment by DavidVentura** [comment]
I just re-ran everything on my notebook (Intel CPU) and it works.. seems it has something to do with virtualbox+AMD. Thanks for linking that issue, consider listing this on the readme

**Comment by syntaxerror** [comment]
Thanks for confirming it works better on Intel.
Agree on adding something about hardware support in readme.

**Comment by DavidVentura** [comment]
It just crashes on AMD. Tested on 2 AMD machines and just crashes on startup

On January 13, 2017 3:14:20 PM GMT-03:00, Rune Rasmussen <notifications@github.com> wrote:
>Thanks for confirming it works better on Intel.
>Agree on adding something about hardware support in readme.
>
>-- 
>You are receiving this because you modified the open/close state.
>Reply to this email directly or view it on GitHub:
>https://github.com/AndrewDryga/vagrant-box-osx/issues/53#issuecomment-272507461

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by mellertson** [comment]
I'm also running AMD and it crashes outputting the following message 
"The guest machine entered an invalid state while waiting for it
to boot. Valid states are 'starting, running'. The machine is in the
'gurumeditation' state. Please verify everything is configured
properly and try again.

If the provider you're using has a GUI that comes with it,
it is often helpful to open that and watch the machine, since the
GUI often has more helpful error messages than Vagrant can retrieve.
For example, if you're using VirtualBox, run `vagrant up` while the
VirtualBox GUI is open.

The primary issue for this error is that the provider you're using
is not properly configured. This is very rarely a Vagrant issue."

**Comment by phosphene** [comment]
I'm also having issue with AMD. Any workarounds?

**Comment by mcandre** [comment]
I'm having luck by disabling nested paging, for what it's worth.
