### ISSUE TITLE
Sierra box won't boot if set memory over 2GB

### ISSUE THREAD

**Issue by jboffel** [AndrewDryga/vagrant-box-osx#55]
Hello,

I tried to allocate more than 2GB of ram but it failed to boot properly. Both guest and host are 64bits system.

Do you know why it is not working?

-----

Actually I have been able to go up to 3GB by raising the video memory from 32 to 64MB with this vagrant instruction:
vb.customize ["modifyvm", :id, "--vram", "<vramsize in MB>"]

And to 4GB if raised to 128MB of video memory...

Don't know why there is such a strict relationship there between video card memory and the system memory...

**Comment by AndrewDryga** [comment]
Can you try to increase RAM manually in VirtualBox UI? And try to boot VM in GUI mode, so you would be able to see what exactly happens inside.

**Comment by jboffel** [comment]
Sorry actually I should have mention that I only ran it in GUI mode.

So basically if you don't adapt the vram accordingly with the ram as I mentioned above, simply the VM won't boot at all, or at least won't output any text after the VM start to boot...

I'm using Mac OS El Capitan with a mac book pro intel graphic chipset by the way.

**Comment by AndrewDryga** [comment]
@jboffel and how about to change it manually? Does it work? Do you have latest VirtualBox/Vagrant versions?

In general, this looks like a vagrant/virtualbox issue, because I know a loot of people that use more than 4Gb RAM in this box, without changing VRAM.

**Comment by AndrewDryga** [comment]
Ill close this issues since there is no additional feedback, and overall bug looks like an VB/vagrant issue.
