### ISSUE TITLE
Worked on the first 'vagrant up'. Now just a black screen and no exit from 'vagrant up'

### ISSUE THREAD

**Issue by nrvale0** [AndrewDryga/vagrant-box-osx#57]
I was able to 'vagrant up' a VM from this box the first time but all subsequent 'up's of the orignal VM or new VMs based on this box have resulted in an OSX booted to nothing but a black screen and I 'vagrant up' never actually exists. I'm running 'vagrant up --debug' but that doesn't yield any useful info.

```pre
$ vagrant box list | grep dyga
http://files.dryga.com/boxes/osx-sierra-0.3.1.box (virtualbox, 0)
$ vagrant --version   
Vagrant 1.9.5
$ VirtualBox --help | head -n1
Oracle VM VirtualBox Manager 5.1.22
```

Ideas?

**Comment by mhsjlw** [comment]
Experiencing the same issue.

**Comment by mhsjlw** [comment]
Ok, this works for me. Set `VM` to the name of the VirtualBox instance (check by going into the GUI), then run this script. Once you start the VM again it will boot (or at least, it did for me after doing this)

```sh
VM=your_vm_name
vboxmanage modifyvm "$VM" --cpuidset 00000001 000106e5 00100800 0098e3fd bfebfbff
vboxmanage setextradata "$VM" "VBoxInternal/Devices/efi/0/Config/DmiSystemProduct" "iMac11,3"
vboxmanage setextradata "$VM" "VBoxInternal/Devices/efi/0/Config/DmiSystemVersion" "1.0"
vboxmanage setextradata "$VM" "VBoxInternal/Devices/efi/0/Config/DmiBoardProduct" "Iloveapple"
vboxmanage setextradata "$VM" "VBoxInternal/Devices/smc/0/Config/DeviceKey" "ourhardworkbythesewordsguardedpleasedontsteal(c)AppleComputerInc"
vboxmanage setextradata "$VM" "VBoxInternal/Devices/smc/0/Config/GetKeyFromRealSMC" 1
```

Hope this helps! Let me know if anyone can figure out what part of this is missing from the Vagrant file as I'd rather not have to run this script :smile:

**Comment by AndrewDryga** [comment]
Most of this stuff is already packaged in Vagrant file, the only difference I've noticed is other [CPU ID](https://github.com/AndrewDryga/vagrant-box-osx/blob/master/src/include/_Vagrantfile#L10).

Is there any reason you changed it? Does [default values](https://github.com/AndrewDryga/vagrant-box-osx/blob/master/src/include/_Vagrantfile#L10) work for you when they are set with this script?

**Comment by mhsjlw** [comment]
No, if I run the Vagrantfile I get a black screen. This script solves the problem.

**Comment by AndrewDryga** [comment]
Does it work If you run it after setting this values:
```
VM=your_vm_name
vboxmanage modifyvm "$VM" --cpuidset 00000001 000206a7 02100800 1fbae3bf bfebfbff
```

**Comment by AndrewDryga** [comment]
It's weird, looks like custom options from Vagrantfile did not apply on your system. What is VirtualBox version?

**Comment by nrvale0** [comment]
The 'setextradata' commands don't fix the black screen on my machine. Also worth noting that I destroyed all VMs and attempted to re-create but even without the setextradata stuff above I'm still getting just a black screen. 

Not sure what else to do to debug.

**Comment by mhsjlw** [comment]
@AndrewDryga sorry for the late response, I have the latest version of VirtualBox (5.1.22)

**Comment by AndrewDryga** [comment]
Seems like a duplicate for #52.

**Comment by mhsjlw** [comment]
Running it on non-Apple hardware will require the `cpuid` field. I guess it's up to you wether you want to enable that ability with your box
