### ISSUE TITLE
EI capitan version and  Maverics link invalid

### ISSUE THREAD

**Issue by r0ysue** [AndrewDryga/vagrant-box-osx#59]
Thanks so much for your generous sharing。
Big help in reverse engineering works .
Do you have a plan to make a EI capitan version ?
And Maverics download link not valid anymore , could you pls update ?

**Comment by AndrewDryga** [comment]
I think once I get hands to rebuild this I'll go straight to the latest available version skipping everything in between. As for Maverics, I don't have a copy anymore (removed when our hosting died), sorry :(.
