### ISSUE TITLE
USB Devices

### ISSUE THREAD

**Issue by skela** [AndrewDryga/vagrant-box-osx#63]
Asking the question here as I can find no known limitation about this mentioned in Virtualbox page, nor any instructions on how to get this working.

Is there any way to get connected iPhone or Android devices to show up in VM ? Anything we can add to the Vagrantfile for this to work?

**Comment by AndrewDryga** [comment]
Hi there,

I've connected USB modem to the running container. It was few years so I may miss something, but USB worked for me without additional changes. 

You can try to play with VirtualBox settings: go to image settings -> `Ports` -> `USB`.

**Comment by skela** [comment]
Ok, then its prob just the USB hub that is my screen that might be the problem here, although devices do show up with lsusb. Perhaps its a USB 3 / USB 2 issue.

**Comment by skela** [comment]
Did it require guest additions to get USB working?

**Comment by dotdoom** [comment]
I got iPhone working and Xcode seeing it fine after enabling USB 3.0 (didn't work with USB 1.0). If you reboot your machine you may need to re-plug iPhone.

Of course you need an extension pack for USB 2.0 / 3.0, available on VirtualBox website.
