### ISSUE TITLE
vagrant up fails

### ISSUE THREAD

**Issue by lth2h** [AndrewDryga/vagrant-box-osx#67]
vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'osx-sierra'...
==> default: Matching MAC address for NAT networking...
==> default: Setting the name of the VM: osx_default_1512415824013_85334
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
    default:
    default: Vagrant insecure key detected. Vagrant will automatically replace
    default: this with a newly generated keypair for better security.
    default:
    default: Inserting generated public key within guest...
    default: Removing insecure key from the guest if it's present...
    default: Key inserted! Disconnecting and reconnecting using new SSH key...
==> default: Machine booted and ready!
==> default: Checking for guest additions in VM...
    default: No guest additions were detected on the base box for this VM! Guest
    default: additions are required for forwarded ports, shared folders, host only
    default: networking, and more. If SSH fails on this machine, please install
    default: the guest additions and repackage the box to continue.
    default:
    default: This is not an error message; everything may continue to work properly,
    default: in which case you may ignore this message.
==> default: Running provisioner: shell...
    default: Running: inline script
==> default: vagrant.d xauthority fix
==> default: /tmp/vagrant-shell: line 1: /home/vagrant/.bash_profile: No such file or directory
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

Obviously on osx .bash_profile isn't going to be in that directory.  Not exactly sure how to tell Vagrant the correct location is /Users/vagrant/.bash_profile

**Comment by AndrewDryga** [comment]
This is a long-overdue issue and most likely not related to the box itself (more to Vagrant configuration). I'll close it for now.
