### ISSUE TITLE
Cannot download vagrant box

### ISSUE THREAD

**Issue by pianetarosso** [AndrewDryga/vagrant-box-osx#68]
**vagrant up** returns this error:

> Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'http://files.dryga.com/boxes/osx-sierra-0.3.1.box' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
==> default: It looks like you attempted to add a box with a URL for the name...
==> default: Instead, use box_url instead of box for box URLs.
==> default: Box file was not detected as metadata. Adding it directly...
==> default: Adding box 'http://files.dryga.com/boxes/osx-sierra-0.3.1.box' (v0) for provider: virtualbox
    default: Downloading: http://files.dryga.com/boxes/osx-sierra-0.3.1.box
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.
> 
> Couldn't resolve host 'files.dryga.com'

**Comment by AndrewDryga** [comment]
Deam it, apparently when we moved to DO Spaces I've forgot to update the DNS. I'll be back with resolution shortly

**Comment by AndrewDryga** [comment]
@pianetarosso Try using `https://vagrant-osx.nyc3.digitaloceanspaces.com/osx-sierra-0.3.1.box`. This is a new address for all boxes. I've updated the link in getting started guide.

I'm closing this issue, but feel free to poke me and I'll reopen it if the problem persists.

**Comment by JakeTrock** [comment]
@AndrewDryga I'm sorry to poke you despite not being the opener, but the box has disappeared again with the same error. If this project has been abandoned, and there is an alternative you know of/use, I'd like to know what it is.
