### ISSUE TITLE
403 error downloading box

### ISSUE THREAD

**Issue by remizyaka** [AndrewDryga/vagrant-box-osx#69]
Can't download box. Link is not working 
```==> default: Adding box 'https://vagrant-osx.nyc3.digitaloceanspaces.com/osx-sierra-0.3.1.box' (v0) for provider: virtualbox
    default: Downloading: https://vagrant-osx.nyc3.digitaloceanspaces.com/osx-sierra-0.3.1.box
    default: Progress: 0% (Rate: 0/s, Estimated time remaining: --:--:--)
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

The requested URL returned error: 403 Forbidden```

**Comment by AndrewDryga** [comment]
DigitalOcean spaces return HTTP 500 for me, I've reached their support and will keep you updated.

**Comment by lecler-i** [comment]
Any mirrors available ?

**Comment by AndrewDryga** [comment]
Not yet, It's not easy to find cheap/sponsored hosting for OS project that needs about 1 TB of traffic per month. Currently, all bets were on DigitalOcean.

**Comment by GennadySpb** [comment]
@AndrewDryga get to try https://wasabi.com/

**Comment by tarekeldeeb** [comment]
The problem is still there. Moreover, the homepage has the yosemite link pointing to siera.

**Comment by lecler-i** [comment]
Can't you create a torrent ? I'm willing to seed with one of my dedicated server if it can help...
I'm pretty sure a lot of people are interested (you saw by the download rate !) and it would be ok to keep the torrent alive...

**Comment by AndrewDryga** [comment]
I posted a rage tweet today (https://twitter.com/andrew_dryga/status/961187099864109056), If nothing happens till end of week, we'll move to torrents. With them It's not possible to download it with a Vagrant command, trough.

**Comment by tarekeldeeb** [comment]
Working now :D

**Comment by AndrewDryga** [comment]
DigitalOcean support reached me few hours ago and told they found pretty nasty bug that occured with my account, problem should be solved now 🎊

**Comment by daniele-athome** [comment]
Hello! It's not working again. I believe torrents would be perfect for this use.

**Comment by ztarem** [comment]
Even when the does work, the max download rate is ~1 MB/s, and the download takes ~4 hours (!!) and breaks periodically.

Please find a better (faster) server, or create a torrent, as many have already suggested.
