### ISSUE TITLE
Corrupted Yosemite Image

### ISSUE THREAD

**Issue by tarekeldeeb** [AndrewDryga/vagrant-box-osx#70]
I tried to download yosemite image two times, and the image seems corrupted: https://vagrant-osx.nyc3.digitaloceanspaces.com/osx-yosemite-0.2.1.box

> #vagrant up 
> ...
> x ./box-disk1.vmdk: gzip decompression failed
> bsdtar.EXE: Error exit delayed from previous errors.

Sierra is downloaded successfully as expected

**Comment by AndrewDryga** [comment]
DigitalOcean storage is no more, please open another issue if it persists for VagrantCloud
