### ISSUE TITLE
Osx resolution on linux

### ISSUE THREAD

**Issue by lundibundi** [AndrewDryga/vagrant-box-osx#72]
I have seen the example vagrant file and this issue https://github.com/AndrewDryga/vagrant-box-osx/issues/44 but resolution in virtualbox still stayed 1024x720. I finally managet to change the resolution with this https://forums.virtualbox.org/viewtopic.php?f=8&t=85084#p404335
and in particular
`vb.customize ["setextradata", :id, "VBoxInternal2/EfiGraphicsResolution", "1920x1080x32"]`
I'd suggest to add this to sample vagrantfile.

Close this issue as you want. 
Big thanks for this box.

**Comment by alexhtml** [comment]
Thank you so much for this information.

**Comment by AndrewDryga** [comment]
Thank you @lundibundi
