### ISSUE TITLE
x ./box-disk1.vmdk: gzip decompression failed

### ISSUE THREAD

**Issue by Aravindios** [AndrewDryga/vagrant-box-osx#74]
Admins-Mac-mini-4:vagrant mac apple$ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'osx-sierra-0.3.1.box' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
==> default: Box file was not detected as metadata. Adding it directly...
==> default: Adding box 'osx-sierra-0.3.1.box' (v0) for provider: virtualbox
    default: Unpacking necessary files from: file:///Users/apple/Desktop/vg/vagrant%20mac/osx-sierra-0.3.1.box
The box failed to unpackage properly. Please verify that the box
file you're trying to add is not corrupted and that enough disk space
is available and then try again.
The output from attempting to unpackage (if any):

x ./box-disk1.vmdk: gzip decompression failed
bsdtar: Error exit delayed from previous errors.

**Comment by inf3rno** [comment]
Same here. It downloaded the box for 2-3 hours and now it starts again. :S Such a bad design...

**Comment by inf3rno** [comment]
Well the .box file takes 13GB and unpacking it takes another 27GB, so you need at least 40GB disk space on your system drive to install this. I downloaded it with browser and saved the box file to a different drive. This way 42GB was enough to install. It stopped by 15GB space left and jumped back to 27GB space left after that on the system drive. With a 120GB SSD it is hard to install.
