### ISSUE TITLE
Vagrant up fails

### ISSUE THREAD

**Issue by VarunRaj94** [AndrewDryga/vagrant-box-osx#75]
It shows this error after vagrant up

The box failed to unpackage properly. Please verify that the box
file you're trying to add is not corrupted and that enough disk space
is available and then try again.
The output from attempting to unpackage (if any):

x ./box-disk1.vmdk: gzip decompression failed
bsdtar: Error exit delayed from previous errors.

**Comment by inf3rno** [comment]
#76

**Comment by AndrewDryga** [comment]
Unfortunately, we don't have a hosting to share the file directly anymore. So I believe this is safe to close as downloading from Vagrant Cloud should work, please reopen otherwise.
