### ISSUE TITLE
Extend documentation with disk space requirements

### ISSUE THREAD

**Issue by inf3rno** [AndrewDryga/vagrant-box-osx#76]
It took me around 30GB on the system drive to unpack the box, after that it jumped back to around 15GB usage. On top of that the box takes another 13GB. With a 120GB SSD for system this is a lot of space, so it would be wise to mention it in the documentation.

By failure it started to download the box file again from zero, which means another 2-3 hour download. This should be added to the documentation too. Maybe downloading it with browser and adding the box locally would be a better advice.

**Comment by AndrewDryga** [comment]
I have added a note that it's slow to download something from Vagrant Cloud and we, unfortunately, we don't have a hosting to share the file directly anymore. So I believe this is safe to close, please reopen otherwise.
