### ISSUE TITLE
What is the hash digest of osx-sierra-0.3.1.box ?

### ISSUE THREAD

**Issue by vegertar** [AndrewDryga/vagrant-box-osx#78]
Hello, I'm under ArchLinux, and I've got gzip decompression failure as same as other ones, but I have enough extra disk space, e.g. 63G.

I downloaded the box several times via vagrant up directly or http downloader like aria2c, but all files seem to be corrupted.

May I have the sha1 digest of current version? The hash you given in #47 is out-of-date, since the file's present Last-Modified date is "Thu, 16 Nov 2017 12:42:14 GMT".

Mine is
```
02087e8e67852b47e24cf899fa5a274a6b4ae561  osx-sierra-0.3.1.box
```

Thank you.

**Comment by dragetd** [comment]
There are my sha1 sums of the files I downloaded yesterday:
e02ea7fff9c3af980bfa733c8feb2e03bf562cfd  osx-sierra-0.3.1.box
6339bf812017b9f0046d9fdda79cc6f3d2ab169a  osx-yosemite-0.2.1.box

**Comment by vegertar** [comment]
> There are my sha1 sums of the files I downloaded yesterday:
> e02ea7fff9c3af980bfa733c8feb2e03bf562cfd osx-sierra-0.3.1.box
> 6339bf812017b9f0046d9fdda79cc6f3d2ab169a osx-yosemite-0.2.1.box

Thank you so much. I have just verified by using a AWS host. This post could be closed.
