### ISSUE TITLE
Minor typo on Vagrant Cloud: "Mavercis"

### ISSUE THREAD

**Issue by mcandre** [AndrewDryga/vagrant-box-osx#82]
Hi Andrew,

Thank you for maintaining these wonderful boxes! I just wanted to mention a small typo on the Vagrant Cloud description, to help spruce up the text!

`Mavercis`

**Comment by AndrewDryga** [comment]
Hey @mcandre, I did not notice that they un-banned the box. It was blocked for years because they were afraid of legal issues of redistributing MacOS and looks like they resolved it. The typo is fixed, I'll see if we can use it as storage for now.
